# Generated by Django 3.2.8 on 2021-11-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(default='intermediate', max_length=20),
            preserve_default=False,
        ),
    ]
