# Generated by Django 3.2.8 on 2021-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211103_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='76036', max_length=10),
            preserve_default=False,
        ),
    ]
