# Generated by Django 3.2.8 on 2021-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
