# Generated by Django 3.2.8 on 2021-11-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('fed_food', models.BooleanField()),
                ('date_fed', models.DateField()),
                ('before_noon', models.BooleanField()),
                ('after_noon', models.BooleanField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
    ]
