# Generated by Django 3.2.8 on 2021-11-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_hardness_ppm', models.IntegerField()),
                ('carbonate_hardness_ppm', models.IntegerField()),
                ('power_of_hydrogen', models.IntegerField()),
                ('nitrites_ppm', models.IntegerField()),
                ('nitrates_ppm', models.IntegerField()),
                ('temperature_fahrenheit', models.IntegerField()),
                ('water_changed', models.BooleanField()),
                ('gallons_water_added', models.IntegerField()),
                ('date_measured', models.DateField()),
                ('before_noon', models.BooleanField()),
                ('after_noon', models.BooleanField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
    ]
