# Generated by Django 3.2.8 on 2021-11-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_parameter',
            name='power_of_hydrogen',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
