# Generated by Django 3.2.8 on 2021-11-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=100)),
                ('is_alive', models.BooleanField()),
                ('number_of_fish', models.IntegerField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
    ]
