# Generated by Django 3.2.8 on 2021-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
